[TASK] Update description of X-UA-Compatible
The meta X-UA-Compatible should not advertise flag "chrome=1" anymore
since the W3C validator will flag it as an error:

    Error: A meta element with an http-equiv attribute whose value is
    X-UA-Compatible must have a content attribute with the value
IE=edge.

"chrome=1" specifies that Google Chrome frame should start if the user
has
it installed. But this flag does not make sense anymore since Google
Chrome
Frame was discontinued in January 2014.

Source: blog.chromium.org/2013/06/retiring-chrome-frame.html